export const mockHotels = [
    {
        id: 1,
        name: 'Hotel Taj Palace',
        address: 'Delhi, India',
        price: 10000,
        image_url: 'https://example.com/taj-palace.jpg',
    },
    {
        id: 2,
        name: 'Leela Palace',
        address: 'Bengaluru, India',
        price: 12000,
        image_url: 'https://example.com/leela-palace.jpg',
    },
    {
        id: 3,
        name: 'Oberoi Hotel',
        address: 'Mumbai, India',
        price: 15000,
        image_url: 'https://example.com/oberoi-hotel.jpg',
    },
    {
        id: 4,
        name: 'ITC Grand Bharat',
        address: 'Gurugram, India',
        price: 22000,
        image_url: 'https://example.com/itc-grand-bharat.jpg',
    },
    {
        id: 5,
        name: 'The Oberoi Udaivilas',
        address: 'Udaipur, India',
        price: 35000,
        image_url: 'https://example.com/oberoi-udaivilas.jpg',
    },
    {
        id: 6,
        name: 'The Leela Mumbai',
        address: 'Mumbai, India',
        price: 18000,
        image_url: 'https://example.com/the-leela-mumbai.jpg',
    },
    {
        id: 7,
        name: 'Radisson Blu Resort',
        address: 'Alibaug, India',
        price: 14000,
        image_url: 'https://example.com/radisson-blu-resort.jpg',
    },
    {
        id: 8,
        name: 'JW Marriott Hotel',
        address: 'New Delhi, India',
        price: 25000,
        image_url: 'https://example.com/jw-marriott-new-delhi.jpg',
    },
    {
        id: 9,
        name: 'The Taj Mahal Palace',
        address: 'Mumbai, India',
        price: 30000,
        image_url: 'https://example.com/taj-mahal-palace.jpg',
    },
    {
        id: 10,
        name: 'The Leela Kovalam',
        address: 'Kovalam, India',
        price: 20000,
        image_url: 'https://example.com/leela-kovalam.jpg',
    },
    {
        id: 11,
        name: 'The Park Chennai',
        address: 'Chennai, India',
        price: 12000,
        image_url: 'https://example.com/the-park-chennai.jpg',
    },
    {
        id: 12,
        name: 'Park Hyatt Chennai',
        address: 'Chennai, India',
        price: 22000,
        image_url: 'https://example.com/park-hyatt-chennai.jpg',
    },
    {
        id: 13,
        name: 'The Westin Goa',
        address: 'Goa, India',
        price: 15000,
        image_url: 'https://example.com/westin-goa.jpg',
    },
    {
        id: 14,
        name: 'Taj Exotica Resort & Spa',
        address: 'Goa, India',
        price: 27000,
        image_url: 'https://example.com/taj-exotica-goa.jpg',
    },
    {
        id: 15,
        name: 'The Imperial New Delhi',
        address: 'New Delhi, India',
        price: 35000,
        image_url: 'https://example.com/imperial-new-delhi.jpg',
    },
    {
        id: 16,
        name: 'Hyatt Centric MG Road',
        address: 'Bengaluru, India',
        price: 20000,
        image_url: 'https://example.com/hyatt-centric-bengaluru.jpg',
    },
    {
        id: 17,
        name: 'Sheraton Grand Bangalore',
        address: 'Bengaluru, India',
        price: 16000,
        image_url: 'https://example.com/sheraton-grand-bangalore.jpg',
    },
    {
        id: 18,
        name: 'The Trident Udaipur',
        address: 'Udaipur, India',
        price: 22000,
        image_url: 'https://example.com/trident-udaipur.jpg',
    },
    {
        id: 19,
        name: 'Radisson Blu Plaza Delhi',
        address: 'New Delhi, India',
        price: 13000,
        image_url: 'https://example.com/radisson-blu-plaza-delhi.jpg',
    },
    {
        id: 20,
        name: 'The Lalit Ashok Bangalore',
        address: 'Bengaluru, India',
        price: 21000,
        image_url: 'https://example.com/lalit-ashok-bengaluru.jpg',
    },
    {
        id: 21,
        name: 'Le Meridien Jaipur Resort & Spa',
        address: 'Jaipur, India',
        price: 17000,
        image_url: 'https://example.com/le-meridien-jaipur.jpg',
    },
    {
        id: 22,
        name: 'The Westin Hyderabad Mindspace',
        address: 'Hyderabad, India',
        price: 21000,
        image_url: 'https://example.com/westin-hyderabad.jpg',
    },
    {
        id: 23,
        name: 'Radisson Blu Hotel, Varanasi',
        address: 'Varanasi, India',
        price: 12000,
        image_url: 'https://example.com/radisson-varanasi.jpg',
    },
    {
        id: 24,
        name: 'The Oberoi Amarvilas',
        address: 'Agra, India',
        price: 35000,
        image_url: 'https://example.com/oberoi-amarvilas.jpg',
    },
    {
        id: 25,
        name: 'Holiday Inn Resort Goa',
        address: 'Goa, India',
        price: 13000,
        image_url: 'https://example.com/holiday-inn-goa.jpg',
    },
];